import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cairo } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/ui/Navbar";
import { StoreProvider } from "@/lip/StoreProvider";
// import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
    <html lang="ar" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} antialiased bg-gray-100`}
      >
        <StoreProvider>
              <Navbar/>
              <main>      
                   {children}
              </main>
        </StoreProvider>
         {/* <ThemeProvider attribute="class" enableSystem={false} defaultTheme="light"> */}
         {/* </ThemeProvider> */}
      </body>
    </html>
    </StoreProvider>
  );
}
